apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-nextcloud
  namespace: nextcloud-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-nextcloud
  template:
    metadata:
      labels:
        app: mariadb-nextcloud
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.4
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb
                  key: root-password
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb
                  key: database
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb
                  key: username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
