apiVersion: v1
kind: Service
metadata:
  name: mariadb-nextcloud
  namespace: nextcloud-staging
spec:
  selector:
    app: mariadb-nextcloud
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
