apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway
  - metallb
  - envoy-gateway
  - cert-manager
  - longhorn
  # später hier ergänzen:
  # - cert-manager
  # - logging
